run `docker-compose exec app yarn add node-sass`
scssファイルを設定すると
```
ERROR in ./app/javascript/packs/pages/contact.vue?vue&type=style&index=0&id=d8d071cc&scoped=true&lang=scss& (./node_modules/css-loader/dist/cjs.js??ref--4-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--4-2!./node_modules/sass-loader/dist/cjs.js??ref--4-3!./node_modules/import-glob-loader!./node_modules/vue-loader/lib??vue-loader-options!./app/javascript/packs/pages/contact.vue?vue&type=style&index=0&id=d8d071cc&scoped=true&lang=scss&)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Missing binding /kokinoue/node_modules/node-sass/vendor/linux-x64-64/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 10.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 14.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/kokinoue/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/kokinoue/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at getDefaultSassImplementation (/kokinoue/node_modules/sass-loader/dist/utils.js:42:10)
    at getSassImplementation (/kokinoue/node_modules/sass-loader/dist/utils.js:50:30)
    at Object.loader (/kokinoue/node_modules/sass-loader/dist/index.js:34:59)
```

が発生。

docker内でnpmは使っていないので
```
$ docker-compose exec app yarn remove node-sass

$ docker-compose exec app yarn add node-sass
```
入れ直したら読み込めた